location ~* ^/(?:xmlrpc\.php|wp-config\.php|readme\.html|license\.txt)$ {
    include snippets/security/444.conf;
}

location ~* ^/(?:wp-admin/includes/|wp-includes/theme-compat/) {
    include snippets/security/444.conf;
}

location ~* ^/(?:wp-includes/js/tinymce/langs/.*\.php|wp-content/uploads/.*\.php)$ {
    include snippets/security/444.conf;
}
